changelog:
  categories:
    - title: Deprecations
      labels:
        - 'release:deprecation'
    - title: Features
      labels:
        - 'release:feature'
    - title: Fixes
      labels:
        - 'release:fix'
    - title: Docs
      labels:
        - 'release:docs'
    - title: Internal changes
      labels:
        - 'release:internal'
    - title: Typos
      labels:
        - 'release:typo'
